<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '',
  'DATABASE_URL' => 'mysql://gemma:gemma_pass123@127.0.0.1:3306/gemma?serverVersion=mariadb-10.5.18&charset=utf8mb4',
);
